### ISSUE TITLE
seems to not work

### ISSUE THREAD

**Issue by crudo0** [Gr4y-r0se/Athena#1]
-k and the api key do not work.
every searchs don't work. from help it's impossible to understand how to use this tool, like how to config the API

**Comment by Gr4y-r0se** [comment]
Hi Crudo0,

The problem with -k should now be fixed, thanks for spotting that! The API is provided by DeHashed, no configuration needed at all from you. Your API key can be found under the settings section of your profile, see this screenshot:

![Screenshot 2020-07-21 at 15 59 00](https://user-images.githubusercontent.com/59868499/88071229-7b5f3e00-cb6b-11ea-80f7-dcb701c8945a.png)

If you have any further complaints or comments, please let me know!
