### ISSUE TITLE
program speed

### ISSUE THREAD

**Issue by Rapid0nion** [Gr4y-r0se/Athena#2]
Hello.

How fast the program works and where can I change it.

**Comment by Gr4y-r0se** [comment]
Hi Rapid0nion,

Could you clarify what you mean by this,

Thanks,

R0se

**Comment by Rapid0nion** [comment]
In dehashed API 2.0 Documentation there is a "Rate limiter in place, Sending more than 5 Requests / 1s (1000MS) will result in a timeout. If misuse and/or abuse is detected by either our automated system or an administrator, you will lose your deposit along with API access."

I don't want to be banned. Therefore, I want to know whether your script exceeds the available work limit.

**Comment by Gr4y-r0se** [comment]
Hi RapidOnion,

The script respects the API speed, and forces a rate limit of 3 requests per second to ensure this is never exceeded.

My apologies for taking so long to respond.
