### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by ItsMalware** [Gr4y-r0se/Athena#4]
Traceback (most recent call last):
  File "/Users/malware_honeypot/Documents/Python/Athena-master/athena.py", line 1, in <module>
    import requests, time, sys, re, numpy, json
ModuleNotFoundError: No module named 'requests'

**Comment by Gr4y-r0se** [comment]
Hey ItsMalware! 

Thank you for your ticket. If you run `pip3 install requests` from your terminal you should fix that error.

Let me know how you get on,

R0se
